/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cbs;

/**
 *
 * @author Ken Zedric Cortes
 */
public class splash extends javax.swing.JFrame {

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loadingnum = new javax.swing.JLabel();
        loadingbar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(126, 14, 9));
        jLabel4.setText("General Santos Ave, Lower Bicutan Taguig City");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 90, 390, 40);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("CSC Borrowing System");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 130, 260, 40);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(126, 14, 9));
        jLabel5.setText("Polytechnic Universtiy of the Philippines");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 60, 350, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kzcor\\Downloads\\pupmaliit.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 50, 100, 100);

        loadingnum.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loadingnum.setText("0%");
        jPanel1.add(loadingnum);
        loadingnum.setBounds(350, 260, 40, 40);

        loadingbar.setForeground(new java.awt.Color(126, 14, 9));
        jPanel1.add(loadingbar);
        loadingbar.setBounds(220, 300, 270, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kzcor\\Downloads\\csclogomaliit.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 50, 100, 100);

        jLabel3.setBackground(new java.awt.Color(126, 14, 9));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kzcor\\Downloads\\loading.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-10, -10, 760, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        setBounds(0, 0, 741, 383);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        splash Splash=new splash();
        Splash.setVisible(true);
        LoginForm loginform = new LoginForm();
        
        try
        {
            for (int i = 0; i <= 100; i++)
            {
                Thread.sleep(40);
                Splash.loadingnum.setText(Integer.toString(i)+"%");
                Splash.loadingbar.setValue(i);
                if (i==100){
                    Splash.setVisible(false);
                    loginform.setVisible(true);
                }   
            }
        } catch (Exception e){}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar loadingbar;
    private javax.swing.JLabel loadingnum;
    // End of variables declaration//GEN-END:variables
}
